/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static sun.jvm.hotspot.HelloWorld.e;

/**
 *
 * @author Admin
 */
public class FormReaderReport extends javax.swing.JFrame {

    /**
     * Creates new form FormReport
     */
    
    private DefaultTableModel tm_reader;

    public FormReaderReport() {
        initComponents();
    }
    
    
    
    public FormReaderReport(Date startDate, Date endDate, String book_id) {
        initComponents();
        
        String[] cols = {"STT", "Mã mượn", "Tên độc giả", "Ngày mượn", "Ngày trả", "Lý do", "Tiền phạt"};
        tm_reader = new DefaultTableModel(cols, 0);
        tableDG.setModel(tm_reader);
        
        try{
        
        Connection conn = Controller.DBConnection.getConnection();
        String sql_select = "SELECT * FROM (SELECT subquery.id, subquery.issue_id, issue_book.reader_id, subquery.book_id, issue_book.issue_date, subquery.return_date, subquery.actual_return_date, subquery.reason, subquery.punish_money FROM (SELECT issue_book_detail.id, issue_book_detail.issue_id, issue_book_detail.book_id, issue_book_detail.return_date, violate.actual_return_date, violate.reason, violate.punish_money FROM issue_book_detail CROSS JOIN violate ON violate.issue_book_detail_id = issue_book_detail.id) AS subquery LEFT JOIN issue_book ON issue_book.issue_id = subquery.issue_id WHERE issue_book.issue_date >= ? AND issue_book.issue_date <= ? AND subquery.book_id = ?) AS subsubquery LEFT JOIN reader ON reader.id = subsubquery.reader_id";
        PreparedStatement pst = conn.prepareStatement(sql_select);  
        pst.setDate(1, new java.sql.Date(startDate.getTime()));
        pst.setDate(2, new java.sql.Date(endDate.getTime()));
        pst.setString(3, book_id);
        ResultSet rs = pst.executeQuery();
        int stt = 0;
        while(rs.next()){
            ++stt;
            String issue_id = rs.getString("issue_id");
            String reader_name = rs.getString("name");
            Date issue_date = rs.getDate("issue_date");
            Date actual_return_date = rs.getDate("actual_return_date");
            String reason = rs.getString("reason");
            int punish_money = rs.getInt("punish_money");
            Object[] ob = {stt, issue_id, reader_name, issue_date, actual_return_date, reason, punish_money};
            tm_reader.addRow(ob);
                
        }
        
        
        sql_select = "SELECT * FROM (SELECT issue_book_detail.issue_id, issue_book_detail.book_id, issue_book.reader_id, issue_book.issue_date, issue_book_detail.return_date, issue_book_detail.status FROM issue_book_detail LEFT JOIN issue_book ON issue_book.issue_id = issue_book_detail.issue_id WHERE issue_book.issue_date >= ? AND issue_book.issue_date <= ? AND issue_book_detail.book_id = ? AND issue_book_detail.status = 'Chưa trả') AS subquery LEFT JOIN reader ON reader.id = subquery.reader_id";
        pst = conn.prepareStatement(sql_select);  
        pst.setDate(1, new java.sql.Date(startDate.getTime()));
        pst.setDate(2, new java.sql.Date(endDate.getTime()));
        pst.setString(3, book_id);
        rs = pst.executeQuery();
        while(rs.next()){
            ++stt;
            String issue_id = rs.getString("issue_id");
            String reader_name = rs.getString("name");
            Date issue_date = rs.getDate("issue_date");
            Date return_date = rs.getDate("return_date");
            String reason = "Chưa trả";
            int punish_money = 0;
            Object[] ob = {stt, issue_id, reader_name, issue_date, return_date, reason, punish_money};
            tm_reader.addRow(ob);
        } 
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDG = new javax.swing.JTable();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống kê");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  CHI TIẾT CÁC LƯỢT MƯỢN SÁCH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tableDG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDG);

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(0, 153, 153));
        rSMaterialButtonCircle1.setText("Quay lại");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rSMaterialButtonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSMaterialButtonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(998, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    
    
   
    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReaderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReaderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReaderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReaderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReaderReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JTable tableDG;
    // End of variables declaration//GEN-END:variables
}
