/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DBConnection;
import com.mysql.cj.xdevapi.Result;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author Admin
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPasswordTextPlaceHolderBeanInfo1 = new rojerusan.RSPasswordTextPlaceHolderBeanInfo();
        rSPasswordTextPlaceHolderBeanInfo2 = new rojerusan.RSPasswordTextPlaceHolderBeanInfo();
        jPanel2 = new javax.swing.JPanel();
        jlb_DANGNHAP = new javax.swing.JLabel();
        jlb_MK = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlb_XNMK = new javax.swing.JLabel();
        jlb_email = new javax.swing.JLabel();
        jlb_TDN = new javax.swing.JLabel();
        jtf_TDN = new app.bolivia.swing.JCTextField();
        jtf_email = new app.bolivia.swing.JCTextField();
        btDangKy = new rojerusan.RSMaterialButtonCircle();
        btDangNhap = new rojerusan.RSMaterialButtonCircle();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jP_MK = new rojerusan.RSPasswordTextPlaceHolder();
        jP_XNMK = new rojerusan.RSPasswordTextPlaceHolder();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký hệ thống");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1523, 828));
        jPanel2.setPreferredSize(new java.awt.Dimension(1520, 828));

        jlb_DANGNHAP.setFont(new java.awt.Font("Sitka Display", 1, 38)); // NOI18N
        jlb_DANGNHAP.setForeground(new java.awt.Color(255, 255, 255));
        jlb_DANGNHAP.setText("ĐĂNG KÝ");
        jlb_DANGNHAP.setToolTipText("");

        jlb_MK.setFont(new java.awt.Font("Sitka Heading", 0, 16)); // NOI18N
        jlb_MK.setForeground(new java.awt.Color(255, 255, 255));
        jlb_MK.setText("Mật khẩu");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background_library.png"))); // NOI18N

        jlb_XNMK.setFont(new java.awt.Font("Sitka Heading", 0, 16)); // NOI18N
        jlb_XNMK.setForeground(new java.awt.Color(255, 255, 255));
        jlb_XNMK.setText("Xác nhận mật khẩu");

        jlb_email.setFont(new java.awt.Font("Sitka Heading", 0, 16)); // NOI18N
        jlb_email.setForeground(new java.awt.Color(255, 255, 255));
        jlb_email.setText("Email");

        jlb_TDN.setFont(new java.awt.Font("Sitka Heading", 0, 16)); // NOI18N
        jlb_TDN.setForeground(new java.awt.Color(255, 255, 255));
        jlb_TDN.setText("Tên đăng nhập");

        jtf_TDN.setBackground(new java.awt.Color(0, 153, 153));
        jtf_TDN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtf_TDN.setPlaceholder("Nhập tên đăng nhập");
        jtf_TDN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_TDNFocusLost(evt);
            }
        });

        jtf_email.setBackground(new java.awt.Color(0, 153, 153));
        jtf_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jtf_email.setPlaceholder("Nhập email");

        btDangKy.setText("Đăng Ký");
        btDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangKyActionPerformed(evt);
            }
        });

        btDangNhap.setText("Đăng nhập");
        btDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangNhapActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secured_Letter_50px.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N

        jP_MK.setBackground(new java.awt.Color(0, 153, 153));
        jP_MK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jP_MK.setForeground(new java.awt.Color(0, 0, 0));
        jP_MK.setPhColor(new java.awt.Color(0, 0, 0));
        jP_MK.setPlaceholder("Nhập mật khẩu");

        jP_XNMK.setBackground(new java.awt.Color(0, 153, 153));
        jP_XNMK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jP_XNMK.setForeground(new java.awt.Color(0, 0, 0));
        jP_XNMK.setPhColor(new java.awt.Color(0, 0, 0));
        jP_XNMK.setPlaceholder("Nhập mật khẩu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlb_MK, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_XNMK, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_email, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jtf_TDN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_MK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_XNMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlb_TDN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(btDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlb_DANGNHAP, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlb_DANGNHAP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jlb_TDN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_TDN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(41, 41, 41)
                .addComponent(jlb_MK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jP_MK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlb_XNMK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jP_XNMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(52, 52, 52)
                .addComponent(btDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1537, 835));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
        public void insertUser(){
        String name = jtf_TDN.getText();
        String pass = String.valueOf(jP_MK.getPassword());
        String confirm = String.valueOf(jP_XNMK.getPassword());
        String email = jtf_email.getText();
                    
       
        try{
            Class.forName( "com.mysql.cj.jdbc.Driver");
            Connection conn = DBConnection.getConnection();         
            String sql_insert = "INSERT INTO users(name, pass, email) VALUES(?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql_insert);

            pst.setString(1, name);
            pst.setString(2, pass);
            pst.setString(3, email);
                  
            int updateRowCount = pst.executeUpdate();
            if(updateRowCount > 0){
                JOptionPane.showMessageDialog(this, "ĐĂNG KÝ THÀNH CÔNG");
            }
            else{
                JOptionPane.showMessageDialog(this, "ĐĂNG KÝ THẤT BẠT");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public boolean validateSignup(){
        String name = jtf_TDN.getText();
        String pass = String.valueOf(jP_MK.getPassword());
        String confirm = String.valueOf(jP_XNMK.getPassword());
        String email = jtf_email.getText();
        
        
        if(name.equals("")){
           JOptionPane.showMessageDialog(this, "TÊN ĐĂNG NHẬP KHÔNG ĐƯỢC ĐỂ TRỐNG");
           return false;      
        }
        
        if(pass.equals("")){
           JOptionPane.showMessageDialog(this, "MẬT KHẨU KHÔNG ĐƯỢC ĐỂ TRỐNG");
           return false;      
        }
        if(confirm.equals("")){
           JOptionPane.showMessageDialog(this, "XÁC NHẬN MẬT KHẨU KHÔNG ĐƯỢC ĐỂ TRỐNG");
           return false;      
        }
        
        if(!pass.equals(confirm)){
           JOptionPane.showMessageDialog(this, "MẬT KHẨU PHẢI KHỚP");
           return false; 
        }
        
        if(email.equals("")){
            JOptionPane.showMessageDialog(this, "EMAIL KHÔNG ĐƯỢC ĐỂ TRỐNG");
           return false;  
        }
        
        
        if(!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")){
           JOptionPane.showMessageDialog(this, "EMAIL KHÔNG CHÍNH XÁC");
           return false;      
        }
        return true;
                                
    }
    
    public boolean checkDuplicateUser(){
        String name = jtf_TDN.getText();
        boolean isExist = false;
        try{
            Class.forName( "com.mysql.cj.jdbc.Driver");
            Connection conn = DBConnection.getConnection();
            String sql_select = "SELECT * FROM users WHERE name = ?";
            PreparedStatement pst = conn.prepareStatement(sql_select);
            pst.setString(1, name);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExist = true;
            }
            else{
                isExist = false; 
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return isExist;
    }
    
    private void btDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangKyActionPerformed
        // TODO add your handling code here:
        if(validateSignup()){
            if(checkDuplicateUser() == false){
                    insertUser();
                    this.dispose();
                    new Login().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "TÊN ĐÃ TỒN TẠI!");
            }
           
        } 
        
    }//GEN-LAST:event_btDangKyActionPerformed

    private void btDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangNhapActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDangNhapActionPerformed

    private void jtf_TDNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_TDNFocusLost
        // TODO add your handling code here:
        if(checkDuplicateUser() == true){
            JOptionPane.showMessageDialog(this, "TÊN ĐÃ TỒN TẠI!");
        }
    }//GEN-LAST:event_jtf_TDNFocusLost
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btDangKy;
    private rojerusan.RSMaterialButtonCircle btDangNhap;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private rojerusan.RSPasswordTextPlaceHolder jP_MK;
    private rojerusan.RSPasswordTextPlaceHolder jP_XNMK;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlb_DANGNHAP;
    private javax.swing.JLabel jlb_MK;
    private javax.swing.JLabel jlb_TDN;
    private javax.swing.JLabel jlb_XNMK;
    private javax.swing.JLabel jlb_email;
    private app.bolivia.swing.JCTextField jtf_TDN;
    private app.bolivia.swing.JCTextField jtf_email;
    private rojerusan.RSPasswordTextPlaceHolderBeanInfo rSPasswordTextPlaceHolderBeanInfo1;
    private rojerusan.RSPasswordTextPlaceHolderBeanInfo rSPasswordTextPlaceHolderBeanInfo2;
    // End of variables declaration//GEN-END:variables
}
